// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateCheckResult>;

export function ClearCodexConfigBackups():Promise<number>;

export function DeleteCodexConfigBackup(arg1:string):Promise<string>;

export function ExportConfig():Promise<string>;

export function GenerateCodexConfigToml():Promise<string>;

export function GetAppConfig():Promise<main.AppConfig>;

export function GetAppVersion():Promise<string>;

export function GetBridgeStatus():Promise<main.BridgeStatusPayload>;

export function GetCodexConfigPath():Promise<string>;

export function GetLogHistory(arg1:number):Promise<Array<main.LogEntry>>;

export function GetOverviewSnapshot():Promise<main.OverviewSnapshot>;

export function ImportConfig(arg1:string):Promise<main.AppConfig>;

export function ListCodexConfigBackups():Promise<Array<string>>;

export function ReadCodexConfigToml():Promise<string>;

export function RestartBridge():Promise<main.BridgeStatusPayload>;

export function RestoreCodexConfigToml():Promise<string>;

export function RestoreCodexConfigTomlFromBackup(arg1:string):Promise<string>;

export function RunHealthCheck():Promise<main.HealthCheckResult>;

export function SaveAppConfig(arg1:main.AppConfig):Promise<main.AppConfig>;

export function StartBridge():Promise<main.BridgeStatusPayload>;

export function StopBridge():Promise<main.BridgeStatusPayload>;

export function WriteCodexConfigToml():Promise<string>;

export function WriteCodexConfigTomlRaw(arg1:string):Promise<string>;
